import { useEffect, useMemo, useState } from 'react';
import { getHistory } from '../utils/historyStorage';

const SERVICES = ['EC2', 'Lambda', 'API Gateway', 'S3', 'IAM', 'RDS', 'CloudWatch', 'VPC', 'CloudFormation', 'ECS', 'EKS', 'ALB', 'Other'];
const SEVERITIES = ['Unknown', 'Low', 'Medium', 'High', 'Critical'];
const API_URL = import.meta.env.VITE_API_URL || 'https://8s5f4an7kb.execute-api.ap-south-1.amazonaws.com';

const asText = (value) => {
  if (value === null || value === undefined || value === '') return '';
  if (typeof value === 'string') return value;
  if (Array.isArray(value)) return value.map((v) => typeof v === 'string' ? v : JSON.stringify(v)).join('\n');
  return JSON.stringify(value, null, 2);
};

const commandsText = (commands) => asText((Array.isArray(commands) ? commands : []).map((c) => typeof c === 'string' ? c : c?.command).filter(Boolean));

function list(value) {
  if (!Array.isArray(value) || value.length === 0) return '_Information not provided._';
  return value.map((item) => `- ${typeof item === 'string' ? item : JSON.stringify(item)}`).join('\n');
}

function numbered(value) {
  if (!Array.isArray(value) || value.length === 0) return '_Information not provided._';
  return value.map((item, i) => `${i + 1}. ${typeof item === 'string' ? item : JSON.stringify(item)}`).join('\n');
}

function reportToMarkdown(report, form) {
  const overview = report?.incident_overview || {};
  const root = report?.root_cause || {};
  const remediation = report?.remediation || {};
  const commands = Array.isArray(report?.diagnostic_commands) ? report.diagnostic_commands : [];
  return `# AWS Incident Report\n\n` +
    `## 1. Incident Overview\n\n- **Incident Title:** ${overview.title || form.title || 'Information not provided.'}\n- **AWS Service:** ${overview.service || form.service || 'Information not provided.'}\n- **Severity:** ${overview.severity || form.severity || 'Unknown'}\n- **Date/Time:** ${overview.timestamp || form.timestamp || 'Information not provided.'}\n- **Status:** ${overview.status || 'Information not provided.'}\n\n` +
    `## 2. Executive Summary\n${report?.executive_summary || 'Information not provided.'}\n\n` +
    `## 3. Impact\n${list(report?.impact)}\n\n` +
    `## 4. Symptoms\n${list(report?.symptoms)}\n\n` +
    `## 5. Evidence\n${list(report?.evidence)}\n\n` +
    `## 6. Root Cause\n### Confirmed Root Cause\n${list(root.confirmed)}\n\n### Probable Root Cause\n${list(root.probable)}\n\n### Unknown / Requires Investigation\n${list(root.unknown)}\n\n` +
    `## 7. Troubleshooting Performed\n${numbered(report?.troubleshooting)}\n\n` +
    `## 8. Diagnostic Commands\n${commands.length ? commands.map((c) => `**SAFE / READ-ONLY**\n\n\`\`\`bash\n${typeof c === 'string' ? c : c.command || ''}\n\`\`\`\n\n${c.description || ''}`).join('\n\n') : '_Information not provided._'}\n\n> Commands are provided for diagnostic guidance only. Review before execution.\n\n` +
    `## 9. Remediation\n### Immediate Remediation\n${list(remediation.immediate)}\n\n### Long-Term Remediation\n${list(remediation.long_term)}\n\n` +
    `## 10. Verification\n${list(report?.verification)}\n\n` +
    `## 11. Rollback Plan\n${list(report?.rollback)}\n\n` +
    `## 12. Prevention\n${list(report?.prevention)}\n\n` +
    `## 13. Post-Incident Checklist\n${list(report?.post_incident_checklist)}\n\n` +
    `---\n**Generated by:** AWS DevOps Incident Helper\n\n_AI-assisted analysis: Validate recommendations against your AWS environment before taking operational action._\n`;
}

function reportToText(report, form) {
  return reportToMarkdown(report, form).replace(/```[a-z]*\n?/g, '').replace(/`/g, '').replace(/^#+\s?/gm, '').replace(/^[-*]\s/gm, '• ').replace(/^\d+\.\s/gm, '• ');
}

function Section({ title, icon, children }) {
  return <section className="analysis-section runbook-section incident-report-section">
    <div className="analysis-section-header"><span className="material-symbols-outlined">{icon}</span><h3>{title}</h3></div>
    <div className="analysis-section-content">{children}</div>
  </section>;
}

function Items({ value, numbered: isNumbered = false }) {
  if (!Array.isArray(value) || !value.length) return <p className="muted-text">Information not provided.</p>;
  const Tag = isNumbered ? 'ol' : 'ul';
  return <Tag className="runbook-list">{value.map((item, i) => <li key={i}>{typeof item === 'string' ? item : JSON.stringify(item)}</li>)}</Tag>;
}

export default function IncidentReportPage({ onNavigate, initialData = null }) {
  const [form, setForm] = useState(() => ({ title: '', service: 'EC2', severity: 'Unknown', description: '', analysis: '', logs: '', diagnostic_commands: '', troubleshooting: '', remediation: '', verification: '', runbook: '', timestamp: '', ...(initialData?.form || {}) }));
  const [report, setReport] = useState(initialData?.report || null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);
  const [sourceId, setSourceId] = useState(initialData?.sourceId || '');

  const history = useMemo(() => getHistory(), []);

  useEffect(() => {
    const id = new URLSearchParams(window.location.search).get('incident');
    if (!id) return;
    const item = getHistory().find((entry) => entry.id === id);
    if (item) loadFromHistory(item);
  }, []);

  function loadFromHistory(item) {
    setSourceId(item.id);
    const a = item.analysis || {};
    const isRunbook = item.type === 'runbook';
    const isLogs = item.type === 'log_analysis';
    setForm({
      title: item.title || '', service: a.service || (isLogs ? 'CloudWatch' : 'EC2'), severity: item.severity || a.severity || 'Unknown',
      description: item.inputSnippet || '', analysis: !isRunbook && !isLogs ? JSON.stringify(a, null, 2) : '',
      logs: isLogs ? item.inputSnippet || '' : '', diagnostic_commands: commandsText(a.aws_commands || a.commands || a.diagnostic_commands),
      troubleshooting: asText(a.troubleshooting_steps || a.troubleshooting_procedure), remediation: asText(a.remediation), verification: asText(a.verification),
      runbook: isRunbook ? JSON.stringify(a, null, 2) : '', timestamp: item.timestamp || '',
    });
    setReport(null);
    setError('');
  }

  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const markdown = useMemo(() => report ? reportToMarkdown(report, form) : '', [report, form]);
  const text = useMemo(() => report ? reportToText(report, form) : '', [report, form]);

  const generate = async (event) => {
    event?.preventDefault();
    setError('');
    if (!form.title.trim() || !form.description.trim()) { setError('Incident title and incident description are required.'); return; }
    setLoading(true);
    try {
      const response = await fetch(`${API_URL}/analyze`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'generate_incident_report', ...form }) });
      const payload = await response.json();
      let data = payload;
      if (data && typeof data.body === 'string') data = JSON.parse(data.body);
      if (!response.ok || data.error) throw new Error(data.error || `API returned HTTP ${response.status}`);
      setReport(data);
    } catch (err) {
      console.error('Incident report generation failed:', err);
      setError(err.message || 'Unable to generate the incident report. Please try again.');
    } finally { setLoading(false); }
  };

  const copy = async (content, label = 'Report') => {
    try { await navigator.clipboard.writeText(content); setCopied(label); setTimeout(() => setCopied(false), 2000); }
    catch { setError('Unable to copy. Please use the download or print options.'); }
  };

  const download = (content, extension, mime) => {
    const blob = new Blob([content], { type: `${mime};charset=utf-8` });
    const url = URL.createObjectURL(blob); const anchor = document.createElement('a');
    const slug = (form.title || 'aws-incident-report').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'aws-incident-report';
    anchor.href = url; anchor.download = `${slug}.${extension}`; anchor.click(); URL.revokeObjectURL(url);
  };

  return <div className="analyzer-page incident-report-page">
    <header className="analyzer-header no-print"><div className="container">
      <div className="analyzer-header-top"><div className="analyzer-breadcrumbs"><button className="back-link" onClick={() => onNavigate('/')}><span className="material-symbols-outlined">arrow_back</span>Back to Home</button><span className="breadcrumb-separator">/</span><span className="breadcrumb-current">Incident Report</span></div><button className="btn btn-sm btn-secondary" onClick={() => onNavigate('/history')}><span className="material-symbols-outlined">history</span>History</button></div>
      <div className="analyzer-brand-heading"><img src="/logo-icon.png" alt="AWS DevOps Incident Helper" className="analyzer-logo-img" /><h1 className="analyzer-title">Incident Export & Reporting</h1></div>
      <p className="analyzer-subtitle">Turn an investigation into a professional, review-first AWS incident report.</p>
    </div></header>

    <main className="analyzer-main"><div className="container">
      <form className="runbook-form-card no-print" onSubmit={generate}>
        <div className="report-source-bar">
          <label>Load from Incident History<select value={sourceId} onChange={(e) => { const item = history.find((x) => x.id === e.target.value); if (item) loadFromHistory(item); }}><option value="">Create manually</option>{history.map((item) => <option key={item.id} value={item.id}>{item.title} — {item.formattedDate}</option>)}</select></label>
          <span className="runbook-safety-note"><span className="material-symbols-outlined">lock</span>All saved data remains in this browser.</span>
        </div>
        <div className="runbook-form-grid">
          <label>Incident Title<input value={form.title} onChange={(e) => update('title', e.target.value)} placeholder="API Gateway 5xx Incident" maxLength={160} /></label>
          <label>AWS Service<select value={form.service} onChange={(e) => update('service', e.target.value)}>{SERVICES.map((s) => <option key={s}>{s}</option>)}</select></label>
          <label>Severity<select value={form.severity} onChange={(e) => update('severity', e.target.value)}>{SEVERITIES.map((s) => <option key={s}>{s}</option>)}</select></label>
          <label>Date/Time<input value={form.timestamp} onChange={(e) => update('timestamp', e.target.value)} placeholder="Optional — do not invent" /></label>
          <label className="runbook-full-field">Incident Description<textarea value={form.description} onChange={(e) => update('description', e.target.value)} rows={5} maxLength={10000} placeholder="Describe the incident, symptoms, affected component, and known evidence..." /></label>
          <label>Incident Analysis<textarea value={form.analysis} onChange={(e) => update('analysis', e.target.value)} rows={4} maxLength={8000} placeholder="Paste Incident Analyzer output" /></label>
          <label>Logs / Evidence<textarea value={form.logs} onChange={(e) => update('logs', e.target.value)} rows={4} maxLength={10000} placeholder="Only evidence supplied by you" /></label>
          <label>Diagnostic Commands<textarea value={form.diagnostic_commands} onChange={(e) => update('diagnostic_commands', e.target.value)} rows={4} maxLength={6000} placeholder="Read-only diagnostic commands" /></label>
          <label>Troubleshooting Steps<textarea value={form.troubleshooting} onChange={(e) => update('troubleshooting', e.target.value)} rows={4} maxLength={6000} placeholder="Steps already performed" /></label>
          <label>Remediation<textarea value={form.remediation} onChange={(e) => update('remediation', e.target.value)} rows={4} maxLength={6000} placeholder="Immediate and long-term remediation" /></label>
          <label>Verification Results<textarea value={form.verification} onChange={(e) => update('verification', e.target.value)} rows={4} maxLength={6000} placeholder="Observed or expected verification" /></label>
          <label>Runbook<textarea value={form.runbook} onChange={(e) => update('runbook', e.target.value)} rows={4} maxLength={8000} placeholder="Optional generated runbook" /></label>
        </div>
        {error ? <div className="error-state-card" role="alert"><strong>{error}</strong></div> : null}
        <div className="runbook-form-actions"><button className="btn btn-lg btn-primary" disabled={loading}>{loading ? 'Generating incident report...' : 'Generate Incident Report'}<span className="material-symbols-outlined">auto_awesome</span></button></div>
      </form>

      {report ? <article className="analysis-container runbook-results incident-report-document">
        <div className="analysis-results-header report-header-row"><div><h2 className="analysis-results-title"><span className="material-symbols-outlined">description</span>{report.incident_overview?.title || form.title || 'AWS Incident Report'}</h2><p className="analysis-results-subtitle">Generated by AWS DevOps Incident Helper • AI-assisted, review before operational action.</p></div><div className="analysis-actions-toolbar no-print"><button className="btn btn-sm btn-secondary" onClick={() => copy(text, 'Report')}>{copied === 'Report' ? 'Copied!' : 'Copy Report'}</button><button className="btn btn-sm btn-secondary" onClick={() => copy(markdown, 'Markdown')}>{copied === 'Markdown' ? 'Copied!' : 'Copy Markdown'}</button><button className="btn btn-sm btn-secondary" onClick={() => download(markdown, 'md', 'text/markdown')}>Download Markdown</button><button className="btn btn-sm btn-secondary" onClick={() => download(text, 'txt', 'text/plain')}>Download TXT</button><button className="btn btn-sm btn-primary" onClick={() => window.print()}>Print Report</button></div></div>
        <div className="runbook-meta"><strong>{report.incident_overview?.severity || form.severity || 'Unknown'}</strong><span>{report.incident_overview?.service || form.service}</span><span>{report.incident_overview?.status || 'Status not provided'}</span></div>
        <Section title="1. Incident Overview" icon="info"><p><strong>Title:</strong> {report.incident_overview?.title || form.title || 'Information not provided.'}</p><p><strong>Service:</strong> {report.incident_overview?.service || form.service || 'Information not provided.'}</p><p><strong>Severity:</strong> {report.incident_overview?.severity || form.severity || 'Unknown'}</p><p><strong>Date/Time:</strong> {report.incident_overview?.timestamp || form.timestamp || 'Information not provided.'}</p><p><strong>Status:</strong> {report.incident_overview?.status || 'Information not provided.'}</p></Section>
        <Section title="2. Executive Summary" icon="summarize"><p>{report.executive_summary || 'Information not provided.'}</p></Section>
        <Section title="3. Impact" icon="warning"><Items value={report.impact} /></Section>
        <Section title="4. Symptoms" icon="troubleshoot"><Items value={report.symptoms} /></Section>
        <Section title="5. Evidence" icon="fact_check"><Items value={report.evidence} /></Section>
        <Section title="6. Root Cause" icon="psychology"><h4>Confirmed Root Cause</h4><Items value={report.root_cause?.confirmed} /><h4>Probable Root Cause</h4><Items value={report.root_cause?.probable} /><h4>Unknown / Requires Investigation</h4><Items value={report.root_cause?.unknown} /></Section>
        <Section title="7. Troubleshooting Performed" icon="format_list_numbered"><Items value={report.troubleshooting} numbered /></Section>
        <Section title="8. Diagnostic Commands" icon="terminal"><div className="runbook-command-list">{Array.isArray(report.diagnostic_commands) && report.diagnostic_commands.length ? report.diagnostic_commands.map((cmd, i) => <div className="runbook-command" key={i}><div><span className="report-readonly-badge">SAFE / READ-ONLY</span><code>{typeof cmd === 'string' ? cmd : cmd.command}</code>{cmd.description ? <p className="muted-text">{cmd.description}</p> : null}</div><button className="btn btn-sm btn-secondary no-print" onClick={() => copy(typeof cmd === 'string' ? cmd : cmd.command, `cmd-${i}`)}>{copied === `cmd-${i}` ? 'Copied!' : 'Copy'}</button></div>) : <p className="muted-text">Information not provided.</p>}</div><div className="runbook-safety-note"><span className="material-symbols-outlined">warning</span>Commands are provided for diagnostic guidance only. Review before execution.</div></Section>
        <Section title="9. Remediation" icon="build"><h4>Immediate Remediation</h4><Items value={report.remediation?.immediate} /><h4>Long-Term Remediation</h4><Items value={report.remediation?.long_term} /></Section>
        <Section title="10. Verification" icon="check_circle"><Items value={report.verification} /></Section>
        <Section title="11. Rollback Plan" icon="undo"><Items value={report.rollback} /></Section>
        <Section title="12. Prevention" icon="shield"><Items value={report.prevention} /></Section>
        <Section title="13. Post-Incident Checklist" icon="checklist"><Items value={report.post_incident_checklist} /></Section>
        <footer className="incident-report-footer"><strong>Generated by:</strong> AWS DevOps Incident Helper<br /><span>This report contains AI-assisted analysis. Validate recommendations against your AWS environment before taking operational action.</span></footer>
      </article> : <div className="empty-history-card no-print"><div className="empty-state-icon"><span className="material-symbols-outlined">description</span></div><h3 className="empty-state-title">No incident report generated yet</h3><p className="empty-state-text">Load an existing investigation or enter incident details manually, then generate a professional report.</p></div>}
    </div></main>
  </div>;
}
